CREATE TABLE USERDRIVER (
id NUMBER(5),
type Varchar2(50),
firstname Varchar2(200),
lastname Varchar2(100),
username Varchar2(100),
password Varchar2(100),
brand Varchar2(100),
model Varchar2(100),
available Number(1));

ALTER TABLE USERDRIVER ADD CONSTRAINT "PK_USERDRIVER" PRIMARY KEY("ID");

CREATE TABLE ROUTE (
PassengerId NUMBER(5),
DriverId NUMBER(5),
ToLocation SDO_GEOMETRY,
FromLocation SDO_GEOMETRY,
StartDate DATE,
EndDate DATE);

ALTER TABLE ROUTE ADD CONSTRAINT "PK_ROUTE" PRIMARY KEY("PASSENGERID", "DRIVERID", "STARTDATE");
ALTER TABLE ROUTE ADD CONSTRAINT "FK_ROUTE_PASSENGERID" FOREIGN KEY("PASSENGERID") REFERENCES USERDRIVER("ID");

